import type { Dish } from '../components/DishCard';

export const SIGNATURE_DISHES: Dish[] = [
  // =================== SOUPS (9 items) ===================
  {
    id: 'soup-1',
    name: 'Tomato Soup (Sweet)',
    teluguName: 'టమాటో సూప్',
    description: 'A comforting cream-based sweet tomato soup served with crispy bread croutons.',
    price: '₹160 / ₹190',
    category: 'Soups',
    image: '/tomato-soup.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'soup-2',
    name: 'Sweet Corn Soup',
    teluguName: 'స్వీట్ కార్న్ సూప్',
    description: 'A creamy, sweet soup packed with tender golden sweet corn kernels and subtle spices.',
    price: '₹160 / ₹190',
    category: 'Soups',
    image: '/sweet-corn-soup.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'soup-3',
    name: 'Veg Corn Soup (Sweet)',
    teluguName: 'వెజ్ కార్న్ సూప్',
    description: 'A delicious combination of sweet corn and fresh farm vegetables in a mildly spiced broth.',
    price: '₹160 / ₹190',
    category: 'Soups',
    image: '/veg-corn-soup.jpg',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'soup-4',
    name: 'Veg Hot & Sour Soup',
    teluguName: 'వెజ్ హాట్ అండ్ సోర్ సూప్',
    description: 'A spicy and tangy soup loaded with finely chopped fresh vegetables and spices.',
    price: '₹180 / ₹210',
    category: 'Soups',
    image: '/veg-hot-and-sour-soup.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'soup-5',
    name: 'Mushroom Soup',
    teluguName: 'మష్రూమ్ సూప్',
    description: 'Creamy and earthy soup made with fresh sautéed mushrooms, herbs, and simmered fresh cream.',
    price: '₹180 / ₹210',
    category: 'Soups',
    image: '/mushroom-soup.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'soup-6',
    name: 'Veg Manchow Soup',
    teluguName: 'వెజ్ మంచో సూప్',
    description: 'A popular hot and spicy Indo-Chinese vegetable soup topped with crispy fried noodles.',
    price: '₹180 / ₹210',
    category: 'Soups',
    image: '/veg-manchow-soup.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'soup-7',
    name: 'Cream Up Mushroom Soup (Sweet)',
    teluguName: 'క్రీమ్ అప్ మష్రూమ్ సూప్',
    description: 'Rich, sweet, and extra creamy soup made with fine chopped mushrooms and fresh cream blend.',
    price: '₹180 / ₹210',
    category: 'Soups',
    image: '/cream-up-mushroom-soup.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'soup-8',
    name: 'Lemon Coriander Soup',
    teluguName: 'లెమన్ కొరియాండర్ సూప్',
    description: 'Light and refreshing soup flavored with fresh lemon juice, coriander, and fine chopped root vegetables.',
    price: '₹160 / ₹190',
    category: 'Soups',
    image: '/lemon-coriander-soup.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'soup-9',
    name: 'Veg Clear Soup',
    teluguName: 'వెజ్ క్లియర్ సూప్',
    description: 'A healthy and clear vegetable broth simmered with fresh farm vegetables and minimal spices.',
    price: '₹160 / ₹190',
    category: 'Soups',
    image: '/veg-clear-soup.jpg',
    rating: 4.3,
    isVegetarian: true,
  },

  // =================== STARTERS (16 items) ===================
  {
    id: 'start-1',
    name: 'Wet Manchuria',
    teluguName: 'వెట్ మంచూరియా',
    description: 'Fried vegetable dumplings simmered in a rich, spicy, and tangy soy-garlic gravy.',
    price: '₹340',
    category: 'Starters',
    image: '/wet-manchuria.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'start-2',
    name: 'Veg Manchuria Dry',
    teluguName: 'వెజ్ మంచూరియా డ్రై',
    description: 'Crispy fried vegetable balls tossed with green chillies, garlic, and soy sauce.',
    price: '₹240/ ₹300',
    category: 'Starters',
    image: '/veg-manchuria-dry.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'start-3',
    name: 'Gobhi Manchuria',
    teluguName: 'గోబీ మంచూరియా',
    description: 'Crispy cauliflower florets tossed in a flavorful Indo-Chinese garlic soy sauce.',
    price: '₹300',
    category: 'Starters',
    image: '/gobhi-manchuria.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'pasand-5',
    name: 'Paneer 65',
    teluguName: 'పనీర్ 65',
    description: 'Spiced cottage cheese chunks marinated, fried, and tossed in yogurt and curry leaves.',
    price: '₹340',
    category: '65 Ki Pasand',
    image: '/paneer-sixty-five-special.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'pasand-6',
    name: 'Baby Corn 65',
    teluguName: 'బేబీ కార్న్ 65',
    description: 'Crispy fried baby corn spears seasoned with ginger, garlic, and special 65 spices.',
    price: '₹340',
    category: '65 Ki Pasand',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'pasand-7',
    name: 'Mushroom 65',
    teluguName: 'మష్రూమ్ 65',
    description: 'Deep-fried fresh mushrooms tossed in spicy yogurt curd and red chilli mixture.',
    price: '₹340',
    category: '65 Ki Pasand',
    image: '/mushroom-sixty-five.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== VEG CURRIES (36 items) ===================
  {
    id: 'curry-1',
    name: 'Mix Vegetable',
    teluguName: 'మిక్స్ వెజిటబుల్',
    description: 'Assorted seasonal fresh vegetables cooked in a rich, home-style onion-tomato gravy.',
    price: '₹290',
    category: 'Veg Curries',
    image: '/mix-vegetable.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-2',
    name: 'Marwadi Veg',
    teluguName: 'మార్వాడి వెజ్',
    description: 'Traditional Marwadi style rich vegetable curry with local spices and yogurt base.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/marwadi-veg.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-3',
    name: 'Mutter Mushroom Masala',
    teluguName: 'మటర్ మష్రూమ్ మసాలా',
    description: 'Juicy fresh mushrooms and green peas simmered in a spiced onion tomato gravy.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/mutter-mushroom-masala.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-4',
    name: 'Mushroom Masala',
    teluguName: 'మష్రూమ్ మసాలా',
    description: 'Fresh sliced mushrooms cooked in a semi-dry spiced masala gravy with fresh herbs.',
    price: '₹340',
    category: 'Veg Curries',
    image: '/mushroom-masala.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-5',
    name: 'Mushroom Paneer',
    teluguName: 'మష్రూమ్ పనీర్',
    description: 'Sautéed mushrooms and tender cottage cheese cubes cooked together in a rich tomato gravy.',
    price: '₹340',
    category: 'Veg Curries',
    image: '/mushroom-paneer.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-6',
    name: 'Methi Chaman',
    teluguName: 'మెంతి చమన్',
    description: 'Cottage cheese grated and cooked in a delicious gravy of fresh fenugreek leaves.',
    price: '₹280',
    category: 'Veg Curries',
    image: '/methi-chaman.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'curry-7',
    name: 'Plain Palak',
    teluguName: 'ప్లెయిన్ పాలక్',
    description: 'Fresh puréed spinach cooked with mild spices and herbs for a healthy option.',
    price: '₹280',
    category: 'Veg Curries',
    image: '/plain-palak.jpg',
    rating: 4.2,
    isVegetarian: true,
  },
  {
    id: 'curry-8',
    name: 'Punjabi Channa Masala',
    teluguName: 'చన్నా మసాలా',
    description: 'Traditional Punjabi style chickpeas simmered in a tangy spiced tomato-onion gravy.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/punjabi-channa-masala.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-9',
    name: 'Paneer Butter Masala',
    teluguName: 'పనీర్ బటర్ మసాలా',
    description: 'Rich tomato, butter, and cashew gravy, flavored with fenugreek and soft paneer cubes.',
    price: '₹310',
    category: 'Veg Curries',
    image: '/paneer-butter-masala.jpg',
    rating: 4.9,
    isVegetarian: true,
  },
  {
    id: 'curry-10',
    name: 'Paneer Kheema Masala',
    teluguName: 'పనీర్ కీమా మసాలా',
    description: 'Minced cottage cheese cooked with onions, tomatoes, and aromatic Indian spices.',
    price: '₹310',
    category: 'Veg Curries',
    image: '/paneer-kheema-masala.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-11',
    name: 'Palak Paneer',
    teluguName: 'పాలక్ పనీర్',
    description: 'Soft cottage cheese cubes cooked in a thick, seasoned spinach puree.',
    price: '₹300',
    category: 'Veg Curries',
    image: '/palak-paneer.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'curry-12',
    name: 'Paneer Chatpata',
    teluguName: 'పనీర్ చట్పటా',
    description: 'Spicy and tangy paneer curry cooked with mixed pickle spices and bell peppers.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/paneer-chatpata.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-13',
    name: 'Paneer Makhanwala',
    teluguName: 'పనీర్ మఖన్వాలా',
    description: 'Rich and buttery paneer cooked in a sweet, velvety tomato sauce with fresh cream.',
    price: '₹310',
    category: 'Veg Curries',
    image: '/paneer-makhanwala.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'curry-14',
    name: 'Paneer Do Pyazza',
    teluguName: 'పనీర్ దో ప్యాజా',
    description: 'Cottage cheese chunks cooked with double amount of onions in spiced gravy.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/paneer-do-pyaza.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-15',
    name: 'Paneer Bhurji',
    teluguName: 'పనీర్ బుర్జీ',
    description: 'Scrambled paneer stir-fried with green chillies, onions, tomatoes, and dry spices.',
    price: '₹310',
    category: 'Veg Curries',
    image: '/paneer-bhurji.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-16',
    name: 'Paneer Patiala (Sweet)',
    teluguName: 'పనీర్ పాటియాలా',
    description: 'Patiala style sweet paneer curry rolled in fried papadum, served in cashew gravy.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/paneer-patiala-sweet.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-17',
    name: 'Paneer Tikka Masala',
    teluguName: 'పనీర్ టిక్కా మసాలా',
    description: 'Tandoor-roasted spiced paneer tikka pieces cooked in rich, tikka gravy.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/paneer-tikka-masala.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'curry-18',
    name: 'Tadka Paneer',
    teluguName: 'తడ్కా పనీర్',
    description: 'Paneer cubes tempered with whole dry red chillies, mustard seeds, and curry leaves.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-19',
    name: 'Tadka Mushroom',
    teluguName: 'తడ్కా మష్రూమ్',
    description: 'Fresh button mushrooms sautéed and tempered in rich ghee and spicy dry chillies.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-20',
    name: 'Stuff Capsicum Masala',
    teluguName: 'స్టఫ్డ్ క్యాప్సికమ్',
    description: 'Capsicum shells stuffed with potato-paneer mash and cooked in spicy masala gravy.',
    price: '₹310',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-21',
    name: 'Stuff Tomato Masala',
    teluguName: 'స్టఫ్డ్ టమాటో',
    description: 'Whole tomatoes hollowed out, stuffed with rich spiced mixture, cooked in curry sauce.',
    price: '₹310',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-22',
    name: 'Punjabi Gobhi Masala',
    teluguName: 'పంజాబీ గోబీ మసాలా',
    description: 'Cauliflower florets and green peas cooked in dry Punjabi style onion tomato gravy.',
    price: '₹310',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-23',
    name: 'Shahi Paneer (Sweet)',
    teluguName: 'షాహీ పనీర్',
    description: 'A royal Mughlai sweet dish of paneer cooked in a rich, creamy white cashew paste.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'curry-24',
    name: 'Schezwan Handi Paneer',
    teluguName: 'షెజ్వాన్ హండీ పనీర్',
    description: 'Cottage cheese cooked in a spicy Indo-Chinese Schezwan gravy inside an earthen pot.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-25',
    name: 'Soya Chaap Paneer',
    teluguName: 'సోయా చాప్ పనీర్',
    description: 'Tender soya chaap rolls and fresh paneer cubes cooked in a unified tomato masala gravy.',
    price: '₹280',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-26',
    name: 'Tomato Chatni',
    teluguName: 'టమాటో చట్నీ',
    description: 'Tangy and mildly sweet tomato dip cooked with mustard seeds, curry leaves, and spices.',
    price: '₹280',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'curry-27',
    name: 'Tomato Curry',
    teluguName: 'టమాటో కర్రీ',
    description: 'Traditional home style tomato preparation cooked in thick tamarind and chilli spices.',
    price: '₹290',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'curry-28',
    name: 'Veg Korma',
    teluguName: 'వెజ్ కుర్మా',
    description: 'Creamy vegetable stew cooked with yoghurt, coconut paste, and aromatic Indian spices.',
    price: '₹290',
    category: 'Veg Curries',
    image: '/veg-kurma.png',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-29',
    name: 'Veg Keema Masala',
    teluguName: 'వెజ్ కీమా మసాలా',
    description: 'Minced mixed vegetables slow cooked with traditional spices, onion, and tomato paste.',
    price: '₹290',
    category: 'Veg Curries',
    image: '/veg-keema-masala.png',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'curry-30',
    name: 'Veg Garlic',
    teluguName: 'వెజ్ గార్లిక్ కర్రీ',
    description: 'Seasonal farm veggies prepared in a bold and aromatic gravy loaded with roasted garlic.',
    price: '₹290',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'curry-31',
    name: 'Veg Do-Pyazza',
    teluguName: 'వెజ్ దో ప్యాజా',
    description: 'Mixed fresh vegetables prepared with a double tempering of sautéed onions.',
    price: '₹310',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'curry-32',
    name: 'Veg Kolhapuri',
    teluguName: 'వెజ్ కొల్హాపూరి',
    description: 'Spicy mixed vegetables cooked in a bold red Maharashtrian Kolhapuri style dry spices.',
    price: '₹320',
    category: 'Veg Curries',
    image: '/veg-kolhapuri.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'curry-33',
    name: 'Veg Jaipuri',
    teluguName: 'వెజ్ జైపూరి',
    description: 'Creamy vegetable gravy prepared in traditional Jaipuri style topped with dry papadum.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-34',
    name: 'Punjabi Gobi Masala',
    teluguName: 'పంజాబీ గోబి మసాలా',
    description: 'Hearty northern style vegetable curry in thick, mildly spiced tomato paste.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-35',
    name: 'Veg Chatpata',
    teluguName: 'వెజ్ చట్పటా',
    description: 'Tangy and spicy mixed vegetables prepared with pickling spices and green bell peppers.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'curry-36',
    name: 'Veg Navratan Kurma (Sweet)',
    teluguName: 'నవరతన్ కుర్మా',
    description: 'A rich sweet curry containing 9 assorted ingredients including fruits, nuts, and veggies.',
    price: '₹320',
    category: 'Veg Curries',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },

  // =================== SPECIAL PANEER CURRIES (5 items) ===================
  {
    id: 'splpaneer-1',
    name: 'Kundan Paneer',
    teluguName: 'కుందన్ పనీర్',
    description: 'Chef\'s special rich curry with paneer stuffed with nuts, served in a delicious cream gravy.',
    price: '₹350',
    category: 'Special Paneer Curries',
    image: '/kundan-paneer.jpg',
    rating: 4.9,
    isVegetarian: true,
  },
  {
    id: 'splpaneer-2',
    name: 'Malai Methi Paneer',
    teluguName: 'మలై మెంతి పనీర్',
    description: 'Cottage cheese cubes cooked in a sweet, creamy white gravy flavored with fenugreek and butter.',
    price: '₹350',
    category: 'Special Paneer Curries',
    image: '/malai-methi-paneer.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'splpaneer-3',
    name: 'Sangai Paneer',
    teluguName: 'సంగై పనీర్',
    description: 'Premium rich curry prepared in traditional Mughlai style with paneer and cashews.',
    price: '₹350',
    category: 'Special Paneer Curries',
    image: '/paneer-sangai.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'splpaneer-4',
    name: 'Paneer Kasha Masala',
    teluguName: 'పనీర్ కషా మసాలా',
    description: 'Minced paneer cooked with onions, tomatoes, and aromatic Indian spices in a thick gravy.',
    price: '₹350',
    category: 'Special Paneer Curries',
    image: '/paneer-kasha-masala.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'splpaneer-5',
    name: 'ZilMil Paneer',
    teluguName: 'జిల్ మిల్ పనీర్',
    description: 'Rich paneer chunks cooked in a colorful gravy with bell peppers, tomatoes, and butter garnish.',
    price: '₹350',
    category: 'Special Paneer Curries',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },

  // =================== SPECIAL VEG CURRIES (4 items) ===================
  {
    id: 'splveg-1',
    name: 'Veg Mandakini',
    teluguName: 'వెజ్ మందాకిని',
    description: 'Fresh mixed vegetables simmered in a special rich, creamy cashew-based gravy.',
    price: '₹340',
    category: 'Special Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'splveg-2',
    name: 'Kandhari Veg',
    teluguName: 'కందరి వెజ్',
    description: 'Exquisite vegetable recipe cooked with dried fruits and a sweet-spicy rich red gravy.',
    price: '₹340',
    category: 'Special Veg Curries',
    image: '/kandhari-veg.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'splveg-3',
    name: 'Haryali Methi Chaman',
    teluguName: 'హరియాళి మెంతి చమన్',
    description: 'Vibrant green spinach and fenugreek leaves curry topped with fresh cream and grated paneer.',
    price: '₹320',
    category: 'Special Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'splveg-4',
    name: 'Zilmil Veg',
    teluguName: 'జిల్ మిల్ వెజ్',
    description: 'Chef\'s special mix veg curry loaded with paneer and baby corn in a rich yellow gravy.',
    price: '₹340',
    category: 'Special Veg Curries',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== ROTI (7 items) ===================
  {
    id: 'roti-1',
    name: 'Tandoori Roti',
    teluguName: 'తందూరి రోటి',
    description: 'Whole wheat flatbread baked directly against clay tandoor walls.',
    price: '₹30',
    category: 'Roti',
    image: '/kothmir-roti.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'roti-2',
    name: 'Butter Roti',
    teluguName: 'బటర్ రోటి',
    description: 'Traditional tandoori wheat flatbread coated with rich fresh cow butter.',
    price: '₹35',
    category: 'Roti',
    image: '/kothmir-butter-roti.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'roti-3',
    name: 'Rumali Roti',
    teluguName: 'రుమాలి రోటి',
    description: 'Soft and paper-thin hand-stretched flatbread cooked on an inverted tandoor grid.',
    price: '₹55',
    category: 'Roti',
    image: '/pudina-butter-roti.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'roti-4',
    name: 'Kothmir Roti',
    teluguName: 'కొత్తిమీర రోటి',
    description: 'Wheat tandoori roti topped with freshly chopped coriander leaves.',
    price: '₹35',
    category: 'Roti',
    image: '/kothmir-roti.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'roti-5',
    name: 'Pudina Roti',
    teluguName: 'పుదీనా రోటి',
    description: 'Tandoor baked wheat flatbread layered with aromatic crushed mint leaves.',
    price: '₹35',
    category: 'Roti',
    image: '/pudina-roti.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'roti-6',
    name: 'Kothmir Butter Roti',
    teluguName: 'కొత్తిమీర బటర్ రోటి',
    description: 'Wheat flatbread topped with freshly chopped coriander and loaded with butter.',
    price: '₹40',
    category: 'Roti',
    image: '/kothmir-butter-roti.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'roti-7',
    name: 'Podina Butter Roti',
    teluguName: 'పుదీనా బటర్ రోటి',
    description: 'Wheat flatbread layered with mint leaves and topped with butter.',
    price: '₹40',
    category: 'Roti',
    image: '/pudina-butter-roti.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== NAAN (11 items) ===================
  {
    id: 'naan-1',
    name: 'Plain Naan',
    teluguName: 'ప్లెయిన్ నాన్',
    description: 'Traditional leavened flatbread freshly baked in tandoor clay-oven.',
    price: '₹50',
    category: 'Naan',
    image: '/plain-naan.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'naan-2',
    name: 'Butter Naan',
    teluguName: 'బటర్ నాన్',
    description: 'Leavened clay-oven flatbread brushed with pure melted butter.',
    price: '₹55',
    category: 'Naan',
    image: '/kothmir-butter-naan.jpg',
    rating: 4.9,
    isVegetarian: true,
  },
  {
    id: 'naan-3',
    name: 'Kothmir Naan',
    teluguName: 'కొత్తిమీర నాన్',
    description: 'Fresh tandoori naan topped with fresh chopped coriander leaves.',
    price: '₹55',
    category: 'Naan',
    image: '/kothmir-naan.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'naan-4',
    name: 'Pudina Butter Naan',
    teluguName: 'పుదీనా బటర్ నాన్',
    description: 'Fresh tandoori naan with mint leaves and cow butter glaze.',
    price: '₹55',
    category: 'Naan',
    image: '/pudina-butter-naan.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'naan-5',
    name: 'Garlic Butter Naan',
    teluguName: 'గార్లిక్ బటర్ నాన్',
    description: 'Highly popular flatbread loaded with chopped fresh garlic cloves and butter glaze.',
    price: '₹60',
    category: 'Naan',
    image: '/kothmir-butter-naan.jpg',
    rating: 4.9,
    isVegetarian: true,
  },
  {
    id: 'naan-6',
    name: 'Pudina Naan',
    teluguName: 'పుదీనా నాన్',
    description: 'Crispy leavened flatbread sprinkled with fresh mint leaves and baked in tandoor.',
    price: '₹50',
    category: 'Naan',
    image: '/pudina-naan.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'naan-7',
    name: 'Baby Naan',
    teluguName: 'బేబీ నాన్',
    description: 'Small sized soft leavened clay-oven flatbread.',
    price: '₹70',
    category: 'Naan',
    image: '/baby-naan.jpg',
    rating: 4.4,
    isVegetarian: true,
  },


  {
    id: 'naan-10',
    name: 'Stuff Naan',
    teluguName: 'స్టఫ్డ్ నాన్',
    description: 'Tandoori naan stuffed with a mix of potato mash, paneer, and local spices.',
    price: '₹75',
    category: 'Naan',
    image: '/masala-kulcha.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'naan-11',
    name: 'Kothmir Butter Naan',
    teluguName: 'కొత్తిమీర బటర్ నాన్',
    description: 'Soft tandoori naan topped with fresh chopped coriander leaves and brushed with melted butter.',
    price: '₹60',
    category: 'Naan',
    image: '/kothmir-butter-naan.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'naan-12',
    name: 'Chatpata Naan',
    teluguName: 'చట్‌పటా నాన్',
    description: 'Spicy stuffed tandoori naan loaded with tangy chatpata masala filling and grilled to perfection.',
    price: '₹75',
    category: 'Naan',
    image: '/pudina-butter-naan.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== PARATHA / KULCHA (8 items) ===================
  {
    id: 'para-1',
    name: 'Aloo Paratha',
    teluguName: 'ఆలూ పరాటా',
    description: 'Wheat flatbread stuffed with spiced mashed potatoes, baked in tandoor.',
    price: '₹75',
    category: 'Paratha / Kulcha',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'para-2',
    name: 'Pudina Paratha',
    teluguName: 'పుదీనా పరాటా',
    description: 'Flaky tandoori layered wheat bread flavored with dried mint powder.',
    price: '₹75',
    category: 'Paratha / Kulcha',
    image: '/pudina-paratha.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'para-3',
    name: 'Plain Paratha',
    teluguName: 'ప్లెయిన్ పరాటా',
    description: 'Tandoor baked layered whole wheat flatbread served hot with ghee.',
    price: '₹80',
    category: 'Paratha / Kulcha',
    image: '/plain-paratha.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'para-4',
    name: 'Laccha Paratha',
    teluguName: 'లచ్చా పరాటా',
    description: 'Multi-layered wheat flatbread baked golden, brushed with cow butter.',
    price: '₹80',
    category: 'Paratha / Kulcha',
    image: '/laccha-paratha.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'para-5',
    name: 'Rajasthani Methi Paratha',
    teluguName: 'రాజస్థానీ మెంతి పరాటా',
    description: 'Layered flatbread cooked with fresh fenugreek leaves and Rajasthani spices.',
    price: '₹75',
    category: 'Paratha / Kulcha',
    image: '/rajasthani-methi-paratha.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'para-6',
    name: 'Paneer Kulcha',
    teluguName: 'పనీర్ కుల్చా',
    description: 'Soft leavened bread stuffed with spiced grated paneer and baked in tandoor.',
    price: '₹80',
    category: 'Paratha / Kulcha',
    image: '/paneer-kulcha.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'para-7',
    name: 'Stuff Kulcha',
    teluguName: 'స్టఫ్డ్ కుల్చా',
    description: 'Special leavened kulcha bread loaded with mixed spices, mashed potatoes, and coriander.',
    price: '₹90',
    category: 'Paratha / Kulcha',
    image: '/masala-kulcha-new.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'para-8',
    name: 'Paneer Paratha',
    teluguName: 'పనీర్ పరాటా',
    description: 'Delicious whole wheat flatbread stuffed with spiced grated cottage cheese and baked to golden perfection.',
    price: '₹85',
    category: 'Paratha / Kulcha',
    image: '/paneer-paratha.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'para-9',
    name: 'Masala Kulcha',
    teluguName: 'మసాలా కుల్చా',
    description: 'Crispy tandoor-baked stuffed bread filled with spiced potato and paneer masala, topped with nigella seeds.',
    price: '₹80',
    category: 'Paratha / Kulcha',
    image: '/masala-kulcha.jpg',
    rating: 4.7,
    isVegetarian: true,
  },

  // =================== RICE (6 items) ===================
  {
    id: 'rice-1',
    name: 'Plain Rice',
    teluguName: 'ప్లెయిన్ రైస్',
    description: 'Perfectly steamed fluffy basmati rice, served fresh and hot.',
    price: '₹190',
    category: 'Rice',
    image: '/plain-rice.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'rice-2',
    name: 'Curd Rice',
    teluguName: 'దద్దోజనం',
    description: 'Comforting rice mixed with thick curd, tempered with mustard seeds, curry leaves, and green chillies.',
    price: '₹210',
    category: 'Rice',
    image: '/curd-rice.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'rice-3',
    name: 'Lemon Rice',
    teluguName: 'నిమ్మకాయ రైస్',
    description: 'Tangy basmati rice tempered with mustard, peanuts, turmeric, and fresh lemon juice.',
    price: '₹210',
    category: 'Rice',
    image: '/lemon-rice.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'rice-4',
    name: 'Jeera Rice',
    teluguName: 'జీరా రైస్',
    description: 'Basmati rice cooked and tempered with cumin seeds and cow ghee.',
    price: '₹210',
    category: 'Rice',
    image: '/jeera-rice.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'rice-5',
    name: 'Tomato Rice',
    teluguName: 'టమాటో రైస్',
    description: 'Spicy rice prepared with tangy tomato gravy, fresh curry leaves, and spices.',
    price: '₹230',
    category: 'Rice',
    image: '/tomato-rice.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'rice-6',
    name: 'Kaju Jeera Rice',
    teluguName: 'కాజు జీరా రైస్',
    description: 'Premium basmati rice tempered with cumin seeds and loaded with toasted cashew nuts.',
    price: '₹250',
    category: 'Rice',
    image: '/kaju-jeera-rice.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'rice-7',
    name: 'Butter Rice',
    teluguName: 'బటర్ రైస్',
    description: 'Fragrant steamed basmati rice sautéed with premium cow butter and fresh green herbs.',
    price: '₹220',
    category: 'Rice',
    image: '/butter-rice.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== FRIED RICE (5 items) ===================
  {
    id: 'fried-1',
    name: 'Veg Fried Rice',
    teluguName: 'వెజ్ ఫ్రైడ్ రైస్',
    description: 'Aromatic wok-fried basmati rice cooked with finely chopped vegetables and soy sauce.',
    price: '₹250 / ₹220',
    category: 'Fried Rice',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'fried-2',
    name: 'Paneer Fried Rice',
    teluguName: 'పనీర్ ఫ్రైడ్ రైస్',
    description: 'Wok-tossed fried rice with tiny cubes of spiced paneer and chopped greens.',
    price: '₹270',
    category: 'Fried Rice',
    image: '/paneer-fried-rice.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'fried-3',
    name: 'Schezwan Fried Rice',
    teluguName: 'షెజ్వాన్ ఫ్రైడ్ రైస్',
    description: 'Spicy and fiery fried rice prepared with custom hot Schezwan pepper sauce.',
    price: '₹270',
    category: 'Fried Rice',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'fried-4',
    name: 'Masala Fried Rice',
    teluguName: 'మసాలా ఫ్రైడ్ రైస్',
    description: 'Indo-Chinese style fried rice spiked with hot Indian garam masala and coriander.',
    price: '₹290',
    category: 'Fried Rice',
    image: '/masala-fried-rice.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'fried-5',
    name: 'Kaju Fried Rice',
    teluguName: 'కాజు ఫ్రైడ్ రైస్',
    description: 'Special fried rice loaded with toasted golden cashew nuts and spring onions.',
    price: '₹290',
    category: 'Fried Rice',
    image: '/kaju-fried-rice.jpg',
    rating: 4.8,
    isVegetarian: true,
  },

  // =================== PULAO (6 items) ===================
  {
    id: 'pull-1',
    name: 'Veg Pulao',
    teluguName: 'వెజ్ పులావ్',
    description: 'Fragrant basmati rice cooked with whole cardamoms, cinnamon, and mixed vegetables.',
    price: '₹290 / ₹210',
    category: 'Pulao',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'pull-2',
    name: 'Corn Kaju Pulao',
    teluguName: 'కార్న్ కాజు పులావ్',
    description: 'Rich sweet-savory rice loaded with sweet corn kernels and whole roasted cashew nuts.',
    price: '₹300',
    category: 'Pulao',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'pull-3',
    name: 'Kashmiri Pulao (Sweet)',
    teluguName: 'కాశ్మీరీ పులావ్',
    description: 'A traditional sweet and fragrant Kashmiri pulao cooked with dry fruits.',
    price: '₹300',
    category: 'Pulao',
    image: '/kashmiri-pulao.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'pull-4',
    name: 'Navratan Pulao (Sweet)',
    teluguName: 'నవరతన్ పులావ్',
    description: 'Royal rice preparation garnished with paneer cubes, dry fruits, and fresh fruits.',
    price: '₹300',
    category: 'Pulao',
    image: '/navratan-pulao.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'pull-5',
    name: 'Punjabi Pulao',
    teluguName: 'పంజాబీ పులావ్',
    description: 'Hearty Punjabi style pulao loaded with chickpeas, carrots, and robust local spices.',
    price: '₹300',
    category: 'Pulao',
    image: '/punjabi-pulao.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'pull-6',
    name: 'Paneer Pulao',
    teluguName: 'పనీర్ పులావ్',
    description: 'Lightly spiced basmati rice pulao cooked with cubes of pan-fried paneer.',
    price: '₹300',
    category: 'Pulao',
    image: '/paneer-pulao.jpg',
    rating: 4.7,
    isVegetarian: true,
  },

  // =================== BIRYANI (8 items) ===================
  {
    id: 'bir-1',
    name: 'Veg Biryani',
    teluguName: 'వెజ్ బిర్యానీ',
    description: 'Richly spiced, layered, and aromatic basmati rice cooked on slow steam with fresh veggies.',
    price: '₹290 / ₹220',
    category: 'Biryani',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'bir-2',
    name: 'Handi Biryani',
    teluguName: 'హండీ బిర్యానీ',
    description: 'Vegetable biryani baked and served inside an earthen clay pot (Handi) to lock in natural flavors.',
    price: '₹300',
    category: 'Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'bir-3',
    name: 'Dum Biryani',
    teluguName: 'వెజ్ దమ్ బిర్యానీ',
    description: 'Slow-cooked traditional Nizami style layered vegetable biryani sealed with dough.',
    price: '₹300',
    category: 'Biryani',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    isVegetarian: true,
  },
  {
    id: 'bir-4',
    name: 'Paneer Biryani',
    teluguName: 'పనీర్ బిర్యానీ',
    description: 'Slow steam-cooked layered rice loaded with marinated soft cubes of cottage cheese.',
    price: '₹310 / ₹240',
    category: 'Biryani',
    image: '/paneer-biryani.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'bir-5',
    name: 'Kaju Biryani',
    teluguName: 'కాజు బిర్యానీ',
    description: 'Royal layered biryani packed with premium golden fried cashews and spices.',
    price: '₹320',
    category: 'Biryani',
    image: '/kaju-biryani.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'bir-6',
    name: 'Mushroom Biryani',
    teluguName: 'మష్రూమ్ బిర్యానీ',
    description: 'Layered aromatic basmati rice cooked with seasoned mushrooms and spices.',
    price: '₹320',
    category: 'Biryani',
    image: '/mushroom-biryani.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'bir-7',
    name: 'Kaju Paneer Biryani',
    teluguName: 'కాజు పనీర్ బిర్యానీ',
    description: 'Premium layered basmati rice biryani with fried cashew nuts and seasoned paneer cubes.',
    price: '₹330',
    category: 'Biryani',
    image: '/kaju-paneer-biryani.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'bir-8',
    name: 'Hyderabad Biryani',
    teluguName: 'హైదరాబాద్ బిర్యానీ',
    description: 'Authentic Hyderabadi style dum biryani with aromatic spices, saffron-infused basmati rice and crispy fried onions.',
    price: '₹320',
    category: 'Biryani',
    image: '/hyderabad-biryani.jpg',
    rating: 4.9,
    isVegetarian: true,
  },

  // =================== PAPAD (5 items) ===================
  {
    id: 'pap-1',
    name: 'Roasted Papad',
    teluguName: 'రోస్టెడ్ అప్పడం',
    description: 'Dry roasted thin lentil crisp, served plain and crunchy.',
    price: '₹40',
    category: 'Papad',
    image: '/roasted-papad.jpg',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'pap-2',
    name: 'Fry Papad',
    teluguName: 'ఫ్రైడ్ అప్పడం',
    description: 'Deep-fried crispy lentil flatbread, crunchy and savory.',
    price: '₹40',
    category: 'Papad',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'pap-3',
    name: 'Masala Papad',
    teluguName: 'మసాలా అప్పడం',
    description: 'Crispy roasted papad topped with chopped onions, tomatoes, green chillies, and chat masala.',
    price: '₹45',
    category: 'Papad',
    image: '/masala-papad.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'pap-4',
    name: 'Special Punjabi Papad',
    teluguName: 'పంజాబీ అప్పడం',
    description: 'Crispy, spicy Amritsari style papad with crushed black pepper kernels.',
    price: '₹85',
    category: 'Papad',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'pap-5',
    name: 'Butter Papad',
    teluguName: 'బటర్ అప్పడం',
    description: 'Crispy roasted papad generously brushed with melted butter for a rich, savory taste.',
    price: '₹45',
    category: 'Papad',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },


  // =================== RAITA (4 items) ===================
  {
    id: 'rai-1',
    name: 'Mix Raita',
    teluguName: 'మిక్స్ రాయితా',
    description: 'Fresh spiced yogurt mixed with finely chopped onion, tomato, and cucumber.',
    price: '₹60',
    category: 'Raita',
    image: '/mix-raita.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'rai-2',
    name: 'Onion Raita',
    teluguName: 'ఆనియన్ రాయితా',
    description: 'Spiced fresh curd mixed with chopped crunchy red onions and mint.',
    price: '₹60',
    category: 'Raita',
    image: '/onion-raita.jpg',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'rai-3',
    name: 'Boondi Raita',
    teluguName: 'బూందీ రాయితా',
    description: 'Whipped salted curd mixed with tiny fried chickpea flour balls (Bundi) and spices.',
    price: '₹70',
    category: 'Raita',
    image: '/bundi-raita.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'rai-4',
    name: 'Curd (Dahi)',
    teluguName: 'పెరుగు',
    description: 'Rich, thick, and fresh home-set cow milk yogurt.',
    price: '₹65',
    category: 'Raita',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },

  // =================== SOFT DRINKS (8 items) ===================
  {
    id: 'drink-1',
    name: 'Butter Milk',
    teluguName: 'మజ్జిగ',
    description: 'Refreshing churned diluted curd spiced with ginger, green chillies, and coriander.',
    price: '₹60 / ₹80',
    category: 'Soft Drinks',
    image: '/butter-milk.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'drink-2',
    name: 'Lassi Sweet',
    teluguName: 'స్వీట్ లస్సీ',
    description: 'Thick, creamy, sweet yogurt beverage served chilled in traditional style.',
    price: '₹80 / ₹100',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1571006682858-a458b8a69388?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'drink-3',
    name: 'Lassi Salted',
    teluguName: 'సాల్టెడ్ లస్సీ',
    description: 'Thick churned fresh curd drink seasoned with salt, cumin powder, and coriander garnish.',
    price: '₹80 / ₹100',
    category: 'Soft Drinks',
    image: '/lassi-salted.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'drink-4',
    name: 'Cold Drink (300ml)',
    teluguName: 'కూల్ డ్రింక్',
    description: 'Assorted aerated soda bottles, served chilled.',
    price: '₹40',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'drink-5',
    name: 'Mineral Water',
    teluguName: 'మినరల్ వాటర్',
    description: 'Packaged drinking water bottle (1 Litre), served chilled.',
    price: '₹20',
    category: 'Soft Drinks',
    image: '/mineral-water.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'drink-6',
    name: 'Fresh Lime Soda (Sweet)',
    teluguName: 'ఫ్రెష్ లైమ్ సోడా (స్వీట్)',
    description: 'Zesty refreshing sweet soda drink with fresh lemon juice.',
    price: '₹70',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'drink-7',
    name: 'Fresh Lime Soda (Salt)',
    teluguName: 'ఫ్రెష్ లైమ్ సోడా (సాల్ట్)',
    description: 'Salted refreshing soda drink with fresh lemon juice.',
    price: '₹70',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'drink-8',
    name: 'Lassi Salted',
    teluguName: 'లస్సీ (ఉప్పు)',
    description: 'Traditional chilled yogurt drink blended with salt, roasted cumin, and fresh coriander.',
    price: '₹80',
    category: 'Soft Drinks',
    image: '/lassi-salted.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== JUMBO FAMILY PACK (3 items) ===================
  {
    id: 'jumbo-1',
    name: 'Paneer Biryani',
    teluguName: 'పనీర్ బిర్యానీ జంబో',
    description: 'Jumbo take-away container of paneer biryani, serves 3-4 people comfortably.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: '/paneer-biryani.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'jumbo-2',
    name: 'Mushroom Biryani',
    teluguName: 'మష్రూమ్ బిర్యానీ జంబో',
    description: 'Jumbo pack of aromatic mushroom biryani, ideal for family take-away.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: '/mushroom-biryani.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'jumbo-3',
    name: 'Veg Biryani',
    teluguName: 'వెజ్ బిర్యానీ జంబో',
    description: 'Special layered vegetable dum biryani in family size pack, packed with rich flavor.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },

  // =================== COMBO FAMILY PACK (2 items) ===================
  {
    id: 'combo-1',
    name: 'Veg Manchuria + Paneer Butter Masala + 8 Butter Rotis + Half Veg Biryani',
description: 'Crispy, spicy Amritsari style papad with crushed black pepper kernels.',
    price: '₹85',
    category: 'Papad',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'pap-5',
    name: 'Butter Papad',
    teluguName: 'బటర్ అప్పడం',
    description: 'Crispy roasted papad generously brushed with melted butter for a rich, savory taste.',
    price: '₹45',
    category: 'Papad',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },


  // =================== RAITA (4 items) ===================
  {
    id: 'rai-1',
    name: 'Mix Raita',
    teluguName: 'మిక్స్ రాయితా',
    description: 'Fresh spiced yogurt mixed with finely chopped onion, tomato, and cucumber.',
    price: '₹60',
    category: 'Raita',
    image: '/mix-raita.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'rai-2',
    name: 'Onion Raita',
    teluguName: 'ఆనియన్ రాయితా',
    description: 'Spiced fresh curd mixed with chopped crunchy red onions and mint.',
    price: '₹60',
    category: 'Raita',
    image: '/onion-raita.jpg',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'rai-3',
    name: 'Boondi Raita',
    teluguName: 'బూందీ రాయితా',
    description: 'Whipped salted curd mixed with tiny fried chickpea flour balls (Bundi) and spices.',
    price: '₹70',
    category: 'Raita',
    image: '/bundi-raita.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'rai-4',
    name: 'Curd (Dahi)',
    teluguName: 'పెరుగు',
    description: 'Rich, thick, and fresh home-set cow milk yogurt.',
    price: '₹65',
    category: 'Raita',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },

  // =================== SOFT DRINKS (8 items) ===================
  {
    id: 'drink-1',
    name: 'Butter Milk',
    teluguName: 'మజ్జిగ',
    description: 'Refreshing churned diluted curd spiced with ginger, green chillies, and coriander.',
    price: '₹60 / ₹80',
    category: 'Soft Drinks',
    image: '/butter-milk.jpg',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'drink-2',
    name: 'Lassi Sweet',
    teluguName: 'స్వీట్ లస్సీ',
    description: 'Thick, creamy, sweet yogurt beverage served chilled in traditional style.',
    price: '₹80 / ₹100',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1571006682858-a458b8a69388?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'drink-3',
    name: 'Lassi Salted',
    teluguName: 'సాల్టెడ్ లస్సీ',
    description: 'Thick churned fresh curd drink seasoned with salt, cumin powder, and coriander garnish.',
    price: '₹80 / ₹100',
    category: 'Soft Drinks',
    image: '/lassi-salted.jpg',
    rating: 4.6,
    isVegetarian: true,
  },
  {
    id: 'drink-4',
    name: 'Cold Drink (300ml)',
    teluguName: 'కూల్ డ్రింక్',
    description: 'Assorted aerated soda bottles, served chilled.',
    price: '₹40',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    isVegetarian: true,
  },
  {
    id: 'drink-5',
    name: 'Mineral Water',
    teluguName: 'మినరల్ వాటర్',
    description: 'Packaged drinking water bottle (1 Litre), served chilled.',
    price: '₹20',
    category: 'Soft Drinks',
    image: '/mineral-water.jpg',
    rating: 4.4,
    isVegetarian: true,
  },
  {
    id: 'drink-6',
    name: 'Fresh Lime Soda (Sweet)',
    teluguName: 'ఫ్రెష్ లైమ్ సోడా (స్వీట్)',
    description: 'Zesty refreshing sweet soda drink with fresh lemon juice.',
    price: '₹70',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'drink-7',
    name: 'Fresh Lime Soda (Salt)',
    teluguName: 'ఫ్రెష్ లైమ్ సోడా (సాల్ట్)',
    description: 'Salted refreshing soda drink with fresh lemon juice.',
    price: '₹70',
    category: 'Soft Drinks',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    isVegetarian: true,
  },
  {
    id: 'drink-8',
    name: 'Lassi Salted',
    teluguName: 'లస్సీ (ఉప్పు)',
    description: 'Traditional chilled yogurt drink blended with salt, roasted cumin, and fresh coriander.',
    price: '₹80',
    category: 'Soft Drinks',
    image: '/lassi-salted.jpg',
    rating: 4.6,
    isVegetarian: true,
  },

  // =================== JUMBO FAMILY PACK (3 items) ===================
  {
    id: 'jumbo-1',
    name: 'Paneer Biryani',
    teluguName: 'పనీర్ బిర్యానీ జంబో',
    description: 'Jumbo take-away container of paneer biryani, serves 3-4 people comfortably.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: '/paneer-biryani.jpg',
    rating: 4.8,
    isVegetarian: true,
  },
  {
    id: 'jumbo-2',
    name: 'Mushroom Biryani',
    teluguName: 'మష్రూమ్ బిర్యానీ జంబో',
    description: 'Jumbo pack of aromatic mushroom biryani, ideal for family take-away.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: '/mushroom-biryani.jpg',
    rating: 4.7,
    isVegetarian: true,
  },
  {
    id: 'jumbo-3',
    name: 'Veg Biryani',
    teluguName: 'వెజ్ బిర్యానీ జంబో',
    description: 'Special layered vegetable dum biryani in family size pack, packed with rich flavor.',
    price: '₹725',
    category: 'Jumbo Family Pack',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    isVegetarian: true,
  },

  // =================== COMBO FAMILY PACK (2 items) ===================
  {
    id: 'combo-1',
    name: 'Veg Manchuria + Paneer Butter Masala + 8 Butter Rotis + Half Veg Biryani',
    teluguName: 'కాంబో ప్యాక్ 1',
    description: 'Full combo pack comprising Veg Manchuria, Paneer Butter Masala, 8pcs of Butter Roti, and Veg Biryani.',
    price: '₹899',
    category: 'Combo Family Pack',
    image: '/butter-milk.jpg',
    rating: 4.9,
    isVegetarian: true,
  }
];

export const GALLERY_PHOTOS = [
  { id: 'g1',  src: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80', title: 'Veg Dum Biryani',        menuCategory: 'Biryani Specials',     menuDishName: 'Veg Dum Biryani' },
  { id: 'g2',  src: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80', title: 'Paneer Butter Masala',   menuCategory: 'Paneer Specials',      menuDishName: 'Paneer Butter Masala' },
  { id: 'g3',  src: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80', title: 'Kaju Paneer Biryani',    menuCategory: 'Biryani Specials',     menuDishName: 'Kaju Paneer Biryani' },
  { id: 'g4',  src: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80', title: 'Paneer Tikka Masala',    menuCategory: 'Paneer Specials',      menuDishName: 'Paneer Tikka Masala' },
  { id: 'g5',  src: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80', title: 'Kaju Butter Masala',     menuCategory: 'Curries',              menuDishName: 'Kaju Butter Masala' },
  { id: 'g6',  src: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80', title: 'Butter Naan',            menuCategory: 'Roti & Naan',          menuDishName: 'Butter Naan' },
  { id: 'g7',  src: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80', title: 'Paneer Patiala',         menuCategory: 'Paneer Specials',      menuDishName: 'Paneer Patiala' },
  { id: 'g8',  src: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80', title: 'Veg Manchuria',          menuCategory: 'Starters',             menuDishName: 'Veg Manchuria Dry' },
  { id: 'g9',  src: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80', title: 'Kashmiri Pulao (Sweet)', menuCategory: 'Biryani Specials',     menuDishName: 'Kashmiri Pulao (Sweet)' },
  { id: 'g10', src: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80', title: 'Jumbo Family Pack',      menuCategory: 'Combos & Family Packs',menuDishName: 'Jumbo Family Pack' },
];


export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Hari Kashyap',
    role: 'Ambience & Pure Veg Food',
    content: 'Service is bit late but ambience and food was amazing. Great pure vegetarian options and tasty gravies.',
    rating: 5,
    source: 'Google Reviews',
    date: '6 months ago',
    avatar: '/avatars/google-avatar-1.png'
  },
  {
    id: 't2',
    name: 'Nilabh Verma',
    role: 'Family Dining & Parking Facility',
    content: "A good family restaurant in Aziz Nagar, Himayat Nagar and Chilkur locality. It's an all vegetarian restaurant and the food quality is good. There is plenty of parking space. The staff is good.",
    rating: 5,
    source: 'Google Reviews',
    date: 'a year ago',
    avatar: '/avatars/google-avatar-2.png'
  },
  {
    id: 't3',
    name: 'Pavan Bhadramraju',
    role: 'Paneer Butter Masala & Butter Naan',
    content: 'We ordered Paneer Butter Masala with Butter Naan, the taste was awesome, the hotel appearance was too good, plenty of vegetarian dishes available here.',
    rating: 5,
    source: 'Google Reviews',
    date: 'a year ago',
    avatar: '/avatars/google-avatar-3.png'
  },
  {
    id: 't4',
    name: 'Rakesh Sharma',
    role: 'Farmhouse Orders & Family Feasts',
    content: 'Good restaurant, friendly staff. Owner is very good and down to earth. Visited with my wife. Loved the food. I also have a farmhouse nearby and we ordered food multiple times from here.',
    rating: 5,
    source: 'Google Reviews',
    date: 'a year ago',
    avatar: '/avatars/google-avatar-4.png'
  },
  {
    id: 't5',
    name: 'Srinivas Mankala',
    role: 'Pure Veg Lunch & Dinner',
    content: 'Great vegetarian restaurant serving very tasty food. Reasonable price and good service.',
    rating: 5,
    source: 'Google Reviews',
    date: '6 months ago',
    avatar: '/avatars/google-avatar-5.png'
  },
  {
    id: 't6',
    name: 'Kedar Shankaar M',
    role: 'Tandoori Breads & Veg Curries',
    content: 'Good those who want veg food can surely go. Neat, silent, tasty veg food served in time. Not too costly.',
    rating: 5,
    source: 'Google Reviews',
    date: 'a year ago',
    avatar: '/avatars/google-avatar-6.png'
  },
  {
    id: 't7',
    name: 'Anand Kumar',
    role: 'Weekend Family Dining',
    content: 'Awesome food and a must go place for all vegetarians. I always go with my family during weekends. Must try. Best vegetarian restaurant nearby. Multiple cuisines for vegetarian lovers.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-7.png'
  },
  {
    id: 't8',
    name: 'Sathvik Krishna',
    role: 'Malai Paneer & Butter Naan',
    content: "This is a very good place for Veg lovers. You'll love the malai paneer and butter naan here. Many varieties available in veg. Enjoy the food!",
    rating: 5,
    source: 'Google Reviews',
    date: '3 years ago',
    avatar: '/avatars/google-avatar-8.png'
  },
  {
    id: 't9',
    name: 'Vijaykant Bilebhavi',
    role: 'Dal Tadka, Dum Aloo & Rotis',
    content: 'Nice atmosphere even in non family section. Of course tasty food, veg noodles 5*, Dal Tadka 5*, Dum aalu 4.3*, Rotis 4*.',
    rating: 5,
    source: 'Google Reviews',
    date: '3 years ago',
    avatar: '/avatars/google-avatar-9.png'
  },
  {
    id: 't10',
    name: 'MOULANA MSK',
    role: 'Special Veg Biryani',
    content: 'Super food, very tasty! Best dining experience on the Chilkur route.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 months ago',
    avatar: '/avatars/google-avatar-10.png'
  },
  {
    id: 't11',
    name: 'Vijay C',
    role: 'Large Group & Family Gatherings',
    content: 'We went with a group of 20 and we were well taken care of. Food was delicious and plentiful.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-11.png'
  },
  {
    id: 't12',
    name: 'Shreeram Menon',
    role: 'Hospitality & Fresh Food',
    content: 'Sambhu has given excellent service, really good food. Great dining experience for our family.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-12.png'
  },
  {
    id: 't13',
    name: 'Srikanth Reddy',
    role: 'Paneer 65 & Kaju Biryani',
    content: 'You will never forget this place once you visit here, food taste is top notch 👌',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-13.png'
  },
  {
    id: 't14',
    name: 'VIJAY KUMAR Naidu',
    role: 'North Indian Thali & Lunch',
    content: 'Lunch is very Tasty here. Great place for authentic dhaba food with quick service.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-14.png'
  },
  {
    id: 't15',
    name: 'Rishab Akilan',
    role: 'Pure Veg Specialties',
    content: 'Really excellent vegetarian dishes, authentic flavors and clean dining area.',
    rating: 5,
    source: 'Google Reviews',
    date: '2 years ago',
    avatar: '/avatars/google-avatar-15.png'
  },
  {
    id: 't16',
    name: 'Subba Raju Mitta',
    role: 'Dhaba Style Dal Makhani & Roti',
    content: 'Good place, authentic dhaba taste and courteous staff service.',
    rating: 5,
    source: 'Google Reviews',
    date: '3 years ago',
    avatar: '/avatars/google-avatar-2.png'
  }
];
